# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build benc Kinesis Advantage 360 Pro'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["adv360pro_left","adv360pro_right"]'
      alphas: '["qwerty"]'
      custom_config: '["#define U_TAPPING_TERM 200"]'
